// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NrJZkKdQ8Gxk_kabrqdGVGnEg1M9Q0E',
    appId: '1:122014876808:web:7680c3e9db134b225c4b3d',
    messagingSenderId: '122014876808',
    projectId: 'dbemiko',
    authDomain: 'dbemiko.firebaseapp.com',
    storageBucket: 'dbemiko.firebasestorage.app',
    measurementId: 'G-DLB2DKEP9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoBshveub7sMiafB8dJZqs8XvLB6Sl134',
    appId: '1:122014876808:android:6c73481c417280235c4b3d',
    messagingSenderId: '122014876808',
    projectId: 'dbemiko',
    storageBucket: 'dbemiko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwSdu2iM45z_t-s3xX7wf9nESlxcV3qo',
    appId: '1:122014876808:ios:9a19b79cfa1aa3295c4b3d',
    messagingSenderId: '122014876808',
    projectId: 'dbemiko',
    storageBucket: 'dbemiko.firebasestorage.app',
    iosBundleId: 'com.example.firebaseGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwSdu2iM45z_t-s3xX7wf9nESlxcV3qo',
    appId: '1:122014876808:ios:9a19b79cfa1aa3295c4b3d',
    messagingSenderId: '122014876808',
    projectId: 'dbemiko',
    storageBucket: 'dbemiko.firebasestorage.app',
    iosBundleId: 'com.example.firebaseGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9NrJZkKdQ8Gxk_kabrqdGVGnEg1M9Q0E',
    appId: '1:122014876808:web:b1f3ff51b306fbda5c4b3d',
    messagingSenderId: '122014876808',
    projectId: 'dbemiko',
    authDomain: 'dbemiko.firebaseapp.com',
    storageBucket: 'dbemiko.firebasestorage.app',
    measurementId: 'G-HCMLLQ0GFL',
  );
}
